//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.1.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------


public enum m68k_register_t {
  M68K_REG_D0,
  M68K_REG_D1,
  M68K_REG_D2,
  M68K_REG_D3,
  M68K_REG_D4,
  M68K_REG_D5,
  M68K_REG_D6,
  M68K_REG_D7,
  M68K_REG_A0,
  M68K_REG_A1,
  M68K_REG_A2,
  M68K_REG_A3,
  M68K_REG_A4,
  M68K_REG_A5,
  M68K_REG_A6,
  M68K_REG_A7,
  M68K_REG_PC,
  M68K_REG_SR,
  M68K_REG_SP,
  M68K_REG_USP,
  M68K_REG_ISP,
  M68K_REG_MSP,
  M68K_REG_SFC,
  M68K_REG_DFC,
  M68K_REG_VBR,
  M68K_REG_CACR,
  M68K_REG_CAAR,
  M68K_REG_PREF_ADDR,
  M68K_REG_PREF_DATA,
  M68K_REG_PPC,
  M68K_REG_IR,
  M68K_REG_CPU_TYPE
}
